controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints: [Rotation, Pitch, Elbow, Wrist_Pitch, Wrist_Roll, Jaw]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    cmd_timeout: 0.5
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5
      Rotation: {trajectory: 0.10, goal: 0.05}
      Pitch: {trajectory: 0.10, goal: 0.05}
      Elbow: {trajectory: 0.10, goal: 0.05}
      Wrist_Pitch: {trajectory: 0.12, goal: 0.06}
      Wrist_Roll: {trajectory: 0.12, goal: 0.06}
      Jaw: {trajectory: 0.15, goal: 0.08}
